// NEXT
import type { Metadata } from "next";

// COMPONENTS
import { Navigation, Logo } from "@/components";

export const metadata: Metadata = {
  title: "The Wild Oasis",
  description: "Generated by create next app",
  icons: ["/logo.png"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <header>
          <Logo />
          <Navigation />
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
